---
- name: Deploy Hello World Application on Kubernetes
  hosts: localhost
  connection: local
  tasks:
    - name: Check if Nginx Ingress is installed
      shell: helm list --filter nginx-ingress --namespace default
      register: helm_result
      ignore_errors: yes

    - name: Install Nginx Ingress using Helm if not installed
      shell: |
        helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
        helm repo update
        helm install nginx-ingress ingress-nginx/ingress-nginx --namespace default
      when: helm_result.stdout == ''
      ignore_errors: yes

    - name: Apply Kubernetes Deployment
      shell: kubectl apply -f ~/Projectk8/deployment.yaml
      args:
        chdir: ~/Projectk8

    - name: Apply Kubernetes Ingress
      shell: kubectl apply -f ~/Projectk8/ingress.yaml
      args:
        chdir: ~/Projectk8

